apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deployhub-tls-cert
  namespace: deployhub-system
  labels:
    deployhub.jeneeldumasia.codes/system: "true"
spec:
  secretName: deployhub-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.deployhub.jeneeldumasia.codes"
    - "deployhub.jeneeldumasia.codes"
