apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: node-exporter-exception
  namespace: observability
spec:
  exceptions:
  - policyName: "disallow-host-namespaces"
    ruleNames:
    - "host-namespaces"
  - policyName: "disallow-host-path"
    ruleNames:
    - "host-path"
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - observability
        names:
        - "*node-exporter*"
