apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Top-level kustomization for ArgoCD.
# ArgoCD syncs path: infra which resolves to this file.
# Every sub-directory that has a kustomization.yaml is listed here.
resources:
  - system/
  - controller/
  - worker/
  - api/
  - scale/
  - ui/
images:
  - name: shipzen-api
    newName: 952994886652.dkr.ecr.us-east-1.amazonaws.com/shipzen/api
    newTag: sha-43d13e9

  - name: shipzen-controller
    newName: 952994886652.dkr.ecr.us-east-1.amazonaws.com/shipzen/controller
    newTag: sha-43d13e9

  - name: shipzen-worker
    newName: 952994886652.dkr.ecr.us-east-1.amazonaws.com/shipzen/worker
    newTag: sha-43d13e9

  - name: shipzen-builder
    newName: ghcr.io/jeneeldumasia/shipzen-builder
    newTag: sha-88e93b4
  - name: shipzen-ui
    newName: 952994886652.dkr.ecr.us-east-1.amazonaws.com/shipzen/ui
    newTag: sha-43d13e9

