apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Top-level kustomization for ArgoCD.
# ArgoCD syncs path: infra which resolves to this file.
# Every sub-directory that has a kustomization.yaml is listed here.
resources:
  - system/
  - controller/
  - worker/
  - api/
  - scale/
  - ui/
images:
  - name: shipzen-api
    newName: 686333686234.dkr.ecr.ap-south-1.amazonaws.com/shipzen/api
    newTag: sha-fc3b84e

  - name: shipzen-controller
    newName: 686333686234.dkr.ecr.ap-south-1.amazonaws.com/shipzen/controller
    newTag: sha-fc3b84e

  - name: shipzen-worker
    newName: 686333686234.dkr.ecr.ap-south-1.amazonaws.com/shipzen/worker
    newTag: sha-fc3b84e

  - name: shipzen-builder
    newName: 686333686234.dkr.ecr.ap-south-1.amazonaws.com/shipzen/builder
    newTag: sha-88e93b4
  - name: shipzen-ui
    newName: 686333686234.dkr.ecr.ap-south-1.amazonaws.com/shipzen/ui
    newTag: sha-fc3b84e

