apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployhub-ui
  namespace: deployhub-system
  labels:
    app: deployhub-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployhub-ui
  template:
    metadata:
      labels:
        app: deployhub-ui
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ui
          image: deployhub-ui:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.deployhub.jeneeldumasia.codes"
            - name: NEXT_PUBLIC_APP_DOMAIN
              value: "deployhub.jeneeldumasia.codes"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
