apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployhub-controller-sa
  namespace: deployhub-system
automountServiceAccountToken: true # Controller needs K8s API access to reconcile resources
