apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipzen-api-sa
  namespace: shipzen-system
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::941718376342:role/ShipZenBuilderRole"
automountServiceAccountToken: true
